# Generated by Django 4.2.6 on 2023-12-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
